### ISSUE TITLE
Inclusion request review in to Conan Center

### ISSUE THREAD

**Issue by danimtb** [nicolastagliani/conan-tinyxml2#1]
## Inclusion Request Review

This is a review for [tinyxml2/6.2.0@noname/stable (nicolastagliani/conan-tinyxml2)](https://github.com/nicolastagliani/conan-tinyxml2) inclusion request to conan-center.
This review follows the [inclusion guidelines of third party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
tinyxml2/6.2.0@noname/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [x] Updated: CMake build helper handles shared option automatically. No need to add this lines: https://github.com/nicolastagliani/conan-tinyxml2/blob/master/conanfile.py#L30
- [x] Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library

#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows
Please include Windows visual studio (AppVeyor) and MacOSX (Travis CI) builds if supported.

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags: Please add some tags in Bintray so people can find this library
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control

### Additional comments

Missing packages for apple-clang 9.1
Missing packages for apple-clang 9.0
Missing packages for Visual Studio 12
Missing packages for Visual Studio 14
Missing packages for Visual Studio 15
Missing packages for gcc 4.9
Missing packages for gcc 5
Missing packages for gcc 6
Missing packages for gcc 7
Missing packages for clang 3.9
Missing packages for clang 4.0

**Comment by danimtb** [comment]
Some recommendations:

- Include a branch per library version and channel: `6.2.0/stable`
- Add your user to package referenc: Instead of `noname` use `nicolastagliani`
- If there is any unsupported platform, please raise an exception in `configure()` method.

**Comment by nicolastagliani** [comment]
I've updated the recipe removing the not needed parts and added some tags in the bintray package that now uses a my name instead of `noname`
I've created a branch and I'm not aware of any unsupported platform

**Comment by nicolastagliani** [comment]
I had to create a different package with a shorter name on bintray (from conan-tinyxml2 to tinyxml2) because the overall upload url was longer than 50 chars and it prevented the artifacts to be uploaded.
Unfortunately I was not able to just rename the package on bintray. 
I will issue a new request for inclusion in conan center the new package and will link this issue there.

**Comment by danimtb** [comment]
Hi @nicolastagliani,

The changes look quite good. Just make sure testing versions are not uploaded to bintray and delete the uploaded ones:

```
conan remove tinyxml2/6.2.0@nicolastagliani/testing -r nicolastaliani_remote
```

I see you have in the travis and appveyor config files this:

```
    CONAN_CHANNEL: "testing"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
```

Please, use `"stable"` as channel and change the stable branch pattern to `"stable/*"`

Finally, be aware that by approving this recipe into conan center you would be the maintainer of issues and community requests.

Thanks a lot @nicolastagliani 😄

**Comment by nicolastagliani** [comment]
I updated the CI files as you suggested and cleaned a little bit my branches here. 

You are welcome 😉

**Comment by danimtb** [comment]
Looking good @nicolastagliani! Approved for Conan Center.

Thanks a lot for the effort 😄
