### ISSUE TITLE
The CMake generated files of tinyxml2 is not exported in the package directories

### ISSUE THREAD

**Issue by A-Alaa** [nicolastagliani/conan-tinyxml2#3]
After Conan installation of tinyxml2, the command of `find_package( tinyxml2 )` doesn't find the package as expected.

The generated CMake files by tinyxml2 build (e.g `tinyxml2Config.cmake` and `tinyxml2Targets.cmake`) are not copied to the package directory.

**Comment by nicolastagliani** [comment]
I know that I'm not packaging the config and target files from tinyxml2 but you can generated the needed files with conan so I didn't think they are really required.
Which generator are you using? Can you add more information on the test case that is not working for you?
Have you tried with cmake_find_package?
I just did a quick test and using that generator I could build a CMake project basically out of the conan documentation (https://docs.conan.io/en/latest/integrations/cmake/cmake_find_package_generator.html)

**Comment by A-Alaa** [comment]
Thanks for following up.
I am using cmake as generator. So, when I include the generated `conanbuildinfo.cmake`, the `find_package( tinyxml2 )` does not work as expected.
I had to make a tailored cmake script to retrieve the configuration files from the build directory instead of the install directory.
I made this auxiliary `Findtinyxml2.cmake`:
```cmake
INCLUDE( FindPackageHandleStandardArgs )

FIND_PATH( tinyxml2_INCLUDE_DIR
  NAMES
    tinyxml2.h
  PATHS
    ${CONAN_INCLUDE_DIRS_TINYXML2}
)

FIND_LIBRARY( tinyxml2_LIBRARY
  NAMES
    ${CONAN_LIBS_TINYXML2}
  PATHS
    ${CONAN_LIB_DIRS_TINYXML2}
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS( tinyxml2 DEFAULT_MSG
  tinyxml2_INCLUDE_DIR
)

IF( tinyxml2_FOUND )
  SET( tinyxml2_INCLUDE_DIRS ${tinyxml2_INCLUDE_DIR} )
  SET( tinyxml2_LIBRARIES ${tinyxml2_LIBRARY} )

  get_filename_component( tinyxml2_CONFIG_PATH ${CONAN_TINYXML2_ROOT} DIRECTORY )
  get_filename_component( tinyxml2_HASH ${CONAN_TINYXML2_ROOT} NAME )
  get_filename_component( tinyxml2_CONFIG_PATH ${tinyxml2_CONFIG_PATH} DIRECTORY )
  set( tinyxml2_CONFIG_PATH  ${tinyxml2_CONFIG_PATH}/build/${tinyxml2_HASH} )
  set( tinyxml2_CONFIG_FILENAME tinyxml2Config.cmake )

  find_file( tinyxml2_CONFIG_DIR
      ${tinyxml2_CONFIG_FILENAME}
    HINTS
      ${tinyxml2_CONFIG_PATH}
  )

  IF( tinyxml2_CONFIG_DIR-NOTFOUND )
    set( tinyxml2_CONFIG "" )
  ELSE()
    set( tinyxml2_CONFIG ${tinyxml2_CONFIG_DIR} )
  ENDIF()

  MARK_AS_ADVANCED(
    tinyxml2_INCLUDE_DIR
    tinyxml2_LIBRARY
    tinyxml2_DIR
    tinyxml2_CONFIG
  )
ELSE()
  SET( tinyxml2_DIR "" CACHE STRING
    "An optional hint to a tinyxml2 directory"
  )
ENDIF()
```

**Comment by nicolastagliani** [comment]
I don't think the cmake generator is supposed to work that way.
Even in the examples on the conan website the find_package is never used with that generator (https://docs.conan.io/en/latest/integrations/cmake/cmake_generator.html)
In your case I think you should use directly something like 
```
target_link_libraries(target CONAN_PKG::tinyxml2)
```

If you want to use a find_package in cmake you should use the cmake_find_package generator. 
Add that generator to your configuration and try again. After doing conan install you should be find a newly generated Findtinyxml2.cmake file (generated by conan and not exported by the library) and that should be enough for you to use find_package in your CMakeLists.txt
